language: php

branches:
  only:
    - /.*/

php:
  - '7.4'

before_install:
  - phpenv config-rm xdebug.ini || return 0

install:
  - composer self-update
  - composer install --no-interaction

script:
  - mkdir build
  - composer ci
