name: Continuous integration

on:
  pull_request: null
  push:
    branches:
      - main

jobs:
  static-analysis:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php-version: ['8.2', '8.3', '8.4']
        command: ['cs', 'stan']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          coverage: none
      - run: composer install --no-interaction --prefer-dist
      - run: composer ${{ matrix.command }}
